commodity: south_african_yellow_maize_jse
regions:
  - country: south_africa
    country_name: "South Africa"
    importance: primary
    locations:
      - region: za_yellow_maize_free_state
        latitude: -28.45
        longitude: 26.80
      - region: za_yellow_maize_north_west
        latitude: -26.66
        longitude: 25.28
      - region: za_yellow_maize_mpumalanga
        latitude: -26.00
        longitude: 30.00
      - region: za_yellow_maize_kwazulu_natal
        latitude: -29.00
        longitude: 30.00
      - region: za_yellow_maize_limpopo
        latitude: -23.90
        longitude: 29.45
