commodity: white_sugar
label_targets:
  - production_quantity
  - area_harvested
  - yield

modeling_grain:
  - country
  - crop_year

first_phase_sources:
  weather:
    - nasa_power
    - chirps
  production:
    - faostat
