"""Render the thin-contract state machine's ASL definition to JSON, OFFLINE.

WHY THIS EXISTS. `infra/terraform/modules/step_functions/main.tf` builds
`local.definition` -- the whole Amazon States Language document for
`leviathan-dev-silver-thin-contract` -- out of HCL comprehensions, `merge()` and
`concat()`. No rendered copy of that document is committed anywhere in the repo
(checked 2026-09-04: the only test that reads the file,
`tests/unit/test_gate_exit_vocabulary.py`, lints HCL TEXT through a brace matcher).
So the properties that actually decide whether the machine WORKS are invisible to
every offline check we had:

  * AWS state names are GLOBAL, and INLINE Map iterator states share that one
    namespace -- a duplicate is `DUPLICATE_STATE_NAME` at UpdateStateMachine time,
    i.e. a failed apply for the ONE machine 25 of 25 schedules run on;
  * D-PR-9 / D-PR-40 narrowed ten `Retry` blocks and the whole safety argument is
    that `States.TaskFailed` is in NONE of them -- a text lint can miss a Retry
    that a comprehension synthesises;
  * `Promote` must be reachable ONLY from `Gate` (INV-6);
  * the definition must fit the 1,048,576-byte CreateStateMachine cap.

HOW IT WORKS, AND WHY IT NEEDS NO AWS. The module's `locals { ... }` block is
lifted verbatim into a throwaway directory, every `resource`/`data` block is left
behind, the three variables `local.definition` reads are declared with defaults,
and one `output` jsonencodes the result. The stripped harness declares NO provider
and NO resource, so `terraform init -backend=false` downloads nothing, contacts
nothing, and needs no credentials -- measured: `.terraform/providers` does not
exist after init.

FIDELITY, STATED. `data.aws_caller_identity.current.account_id` is referenced only
inside the IAM policy resource, never inside `local.definition`, so stripping the
data source cannot change the rendered shape. The only harness-vs-prod difference
in the rendered JSON is the account digits inside the SNS `TopicArn` values.

USE:
    python scripts/ops/render_sfn_definition.py --out-json rendered.json
    python scripts/ops/render_sfn_definition.py --src <some other main.tf>

`tests/unit/test_thin_contract_fetch_degraded.py` imports `render_definition()`
and skips when `terraform` is not on PATH.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SFN_MAIN_TF = REPO_ROOT / "infra" / "terraform" / "modules" / "step_functions" / "main.tf"

# AWS CreateStateMachine / UpdateStateMachine hard cap on the definition document.
DEFINITION_SIZE_CAP_BYTES = 1048576

# Declared with defaults so the harness needs no tfvars. These are the ONLY variables
# `local.definition` reads; `aws_region`, `pass_role_arns`, `silver_pipeline_topic_arn`
# and `log_retention_days` are read only by the stripped resources.
_HARNESS_VARIABLES = """# GENERATED by scripts/ops/render_sfn_definition.py.
# Throwaway harness -- do not edit, do not commit.
variable "project_name" {
  type    = string
  default = "leviathan"
}
variable "environment" {
  type    = string
  default = "dev"
}
variable "alerts_topic_arn" {
  type    = string
  default = "arn:aws:sns:us-east-1:000000000000:leviathan-dev-alerts"
}
variable "map_max_concurrency" {
  type    = number
  default = 1
}

"""

_HARNESS_OUTPUT = """

output "definition_json" {
  value = jsonencode(local.definition)
}
"""


def build_harness(src_tf: Path, outdir: Path) -> Path:
    """Write a provider-free terraform dir that renders `local.definition` and nothing else.

    The slice is anchored on the `locals {` opener and the FIRST top-level `resource`
    block after it; both anchors are asserted, so a future reshuffle of the module
    fails loudly here instead of rendering a truncated definition.
    """
    src = src_tf.read_text(encoding="utf-8")

    start = src.find("\nlocals {")
    if start < 0:
        raise SystemExit("render_sfn_definition: no top-level 'locals {' block in %s" % src_tf)
    tail = re.search(r"^resource\s+\"", src[start:], re.M)
    if tail is None:
        raise SystemExit("render_sfn_definition: no top-level 'resource' block after locals")

    lines = src[start:start + tail.start()].rstrip().splitlines()
    # drop the comment banner that introduces the first resource
    while lines and (lines[-1].lstrip().startswith("#") or not lines[-1].strip()):
        lines.pop()
    body = "\n".join(lines)
    if not body.rstrip().endswith("}"):
        raise SystemExit("render_sfn_definition: sliced locals block does not close cleanly")
    if "local.definition" not in body and "definition = {" not in body:
        raise SystemExit("render_sfn_definition: sliced block does not define local.definition")

    outdir.mkdir(parents=True, exist_ok=True)
    (outdir / "main.tf").write_text(
        _HARNESS_VARIABLES + body + _HARNESS_OUTPUT, encoding="utf-8", newline="\n"
    )
    return outdir / "main.tf"


def _tf(outdir: Path, *args: str) -> subprocess.CompletedProcess:
    proc = subprocess.run(
        ["terraform", "-chdir=%s" % outdir, *args],
        capture_output=True,
        text=True,
        timeout=300,
    )
    if proc.returncode != 0:
        raise SystemExit(
            "render_sfn_definition: terraform %s failed (rc=%d)\n%s\n%s"
            % (" ".join(args), proc.returncode, proc.stdout, proc.stderr)
        )
    return proc


def render_definition(src_tf: Path | None = None, workdir: Path | None = None) -> dict:
    """Return the rendered ASL definition as a dict. Requires `terraform` on PATH."""
    if shutil.which("terraform") is None:
        raise SystemExit("render_sfn_definition: terraform is not on PATH")
    src_tf = Path(src_tf) if src_tf is not None else SFN_MAIN_TF

    tmp = None
    if workdir is None:
        tmp = tempfile.TemporaryDirectory(prefix="sfn_render_")
        workdir = Path(tmp.name)
    try:
        build_harness(src_tf, Path(workdir))
        # -backend=false: no state backend is configured or needed; nothing is downloaded
        # because the harness declares no provider and no resource.
        _tf(Path(workdir), "init", "-backend=false", "-input=false", "-no-color")
        _tf(Path(workdir), "validate", "-no-color")
        _tf(Path(workdir), "apply", "-auto-approve", "-input=false", "-no-color")
        raw = _tf(Path(workdir), "output", "-raw", "-no-color", "definition_json").stdout
        return json.loads(raw)
    finally:
        if tmp is not None:
            tmp.cleanup()


def _is_states_map(node: object) -> bool:
    """True when `node` is a `{name: state}` map, i.e. every value is a state object."""
    return (
        isinstance(node, dict)
        and bool(node)
        and all(isinstance(v, dict) and "Type" in v for v in node.values())
    )


def state_containers(definition: dict) -> list[dict]:
    """Every `{name: state}` map in the document, at ANY depth, outermost first.

    STRUCTURAL, not a whitelist of keys, and that is the point. ASL nests states in
    at least three places -- `ItemProcessor.States` (the INLINE Map form this module
    uses), `Iterator.States` (the legacy Map key AWS still accepts) and
    `Parallel.Branches[].States` -- and all of them share the ONE global name space
    that `DUPLICATE_STATE_NAME` is enforced on. A walker that descends exactly one
    level into `ItemProcessor` is CORRECT for today's document and passes VACUOUSLY
    the day a Map is nested or a Parallel appears, which is the worst failure mode a
    pin can have. This walks every dict and list and yields any `States` map it
    finds, so a new nesting form needs no edit here.
    """
    found: list[dict] = []

    def walk(node: object) -> None:
        if isinstance(node, dict):
            inner = node.get("States")
            if _is_states_map(inner):
                found.append(inner)
            for value in node.values():
                walk(value)
        elif isinstance(node, list):
            for value in node:
                walk(value)

    walk(definition)
    return found


def state_names(definition: dict) -> tuple[list[str], list[str]]:
    """(top-level names, every NESTED name). AWS shares ONE namespace across both."""
    top = list(definition["States"])
    nested: list[str] = []
    for container in state_containers(definition):
        if container is definition["States"]:
            continue
        nested.extend(container)
    return top, nested


def retry_blocks(definition: dict) -> dict:
    """Every `Retry` in the definition, keyed by the state that owns it, at any depth."""
    out: dict = {}
    for container in state_containers(definition):
        for name, value in container.items():
            if "Retry" in value:
                out[name] = value["Retry"]
    return out


def definition_size_bytes(definition: dict) -> int:
    """The compact-JSON byte length AWS measures against DEFINITION_SIZE_CAP_BYTES."""
    return len(json.dumps(definition, separators=(",", ":")).encode("utf-8"))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--src", default=str(SFN_MAIN_TF), help="module main.tf to render")
    ap.add_argument("--out-json", default=None, help="write the rendered definition here")
    ap.add_argument("--keep-dir", default=None, help="keep the harness in this directory")
    args = ap.parse_args(argv)

    definition = render_definition(
        Path(args.src), Path(args.keep_dir) if args.keep_dir else None
    )
    blob = json.dumps(definition, indent=2, sort_keys=True)
    size = definition_size_bytes(definition)

    top, nested = state_names(definition)
    names = top + nested
    dupes = sorted({n for n in names if names.count(n) > 1})
    retries = retry_blocks(definition)

    print("source        : %s" % args.src)
    print("definition    : %d bytes compact, %.3f%% of the %d-byte cap"
          % (size, 100.0 * size / DEFINITION_SIZE_CAP_BYTES, DEFINITION_SIZE_CAP_BYTES))
    print("state names   : top=%d nested=%d total=%d unique=%d duplicates=%s"
          % (len(top), len(nested), len(names), len(set(names)), dupes or "NONE"))
    print("containers    : %d States maps walked" % len(state_containers(definition)))
    print("retry blocks  : %d" % len(retries))
    for name in sorted(retries):
        print("   %-26s %s" % (name, retries[name][0]["ErrorEquals"]))
    print("States.TaskFailed in any Retry: %s"
          % any("States.TaskFailed" in json.dumps(r) for r in retries.values()))
    print("Promote entered from          : %s"
          % sorted(k for k, v in definition["States"].items() if v.get("Next") == "Promote"))

    if args.out_json:
        Path(args.out_json).write_text(blob + "\n", encoding="utf-8", newline="\n")
        print("wrote %s (%d bytes pretty)" % (args.out_json, len(blob) + 1))

    # THE TWO GATES THAT LIVE HERE AND NOWHERE ELSE. Both are AWS hard limits on
    # the ONE machine 25 of 25 schedules run on, both are invisible to
    # `terraform validate`, and both are rejections at UpdateStateMachine time
    # (i.e. a failed apply). This CLI is a rollout step, so it exits non-zero
    # rather than printing a number nobody reads.
    failures = []
    if dupes:
        failures.append("DUPLICATE_STATE_NAME: %s" % dupes)
    if size >= DEFINITION_SIZE_CAP_BYTES:
        failures.append("definition %d bytes >= the %d-byte cap"
                        % (size, DEFINITION_SIZE_CAP_BYTES))
    for line in failures:
        print("GATE FAILED   : %s" % line)
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
