-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over gold/training_windows/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS gold_training_windows (
    commodity          string,
    tier               string,
    n_features         bigint,
    label_first_year   bigint,
    label_last_year    bigint,
    n_label_years      bigint,
    dense_start_year   double,
    dense_window_years bigint,
    present_families   string
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/gold/training_windows/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
