-- GENERATED by leviathan.features.ddl -- do not edit by hand.
-- Long-format feature spine: one row per (commodity, country, crop_year, feature).
-- Schema is fixed; adding features never requires a DDL change.
CREATE EXTERNAL TABLE IF NOT EXISTS gold_feature_spine (
    country     string,
    crop_year   int,
    feature     string,
    value       double,
    is_label    boolean,
    event_time  date
)
PARTITIONED BY (commodity string)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/gold/feature_spine/'
TBLPROPERTIES (
    'parquet.compression' = 'SNAPPY',
    'projection.enabled' = 'true',
    'projection.commodity.type' = 'enum',
    'projection.commodity.values' = 'cocoa,corn_cbot,campinas_corn_reference_bmf,french_wheat_matif,french_maize_matif,hard_red_winter_wheat_kcbt,hard_red_spring_wheat_mgex,soft_red_winter_wheat_cbot,rough_rice_cbot,south_african_white_maize_jse,south_african_yellow_maize_jse,soybeans_cbot,soybean_meal_cbot,soybean_oil_cbot,soybeans_no_1_dce,soybeans_no_2_dce,soybean_meal_dce,soybean_oil_dce,french_rapeseed_matif,canola_ice,rapeseed_oil_zce,rapeseed_meal_zce,malaysian_crude_palm_oil_cme,palm_olein_dce,brazilian_arabica_coffee,arabica_coffee,robusta_coffee,cotton,raw_sugar,white_sugar,frozen_orange_juice',
    'storage.location.template' = 's3://leviathan-dev-shahem-001/gold/feature_spine/commodity=${commodity}/'
);
