-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over gold/feature_catalog/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS gold_feature_catalog (
    feature   string,
    scope     string,
    group     string,
    commodity string,
    is_label  boolean
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/gold/feature_catalog/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
