-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/sagis_cec/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_sagis_cec (
    production_year    bigint,
    report_month       bigint,
    release_date       string,
    season_type        string,
    crop               string,
    scope              string,
    estimate_number    bigint,
    area_planted_ha    double,
    current_estimate_t double,
    prior_estimate_t   double,
    prior_year_final_t double,
    revision_t         double,
    revision_pct       double,
    revision_surprise  double,
    source             string
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/sagis_cec/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
