-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/nass_citrus/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_nass_citrus (
    season              string,
    release_date        string,
    report_month        bigint,
    crop                string,
    state               string,
    forecast_1000_boxes double,
    revision_1000_boxes double,
    hlb_trend_factor    double,
    source              string
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/nass_citrus/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
