-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/nass_crop_progress/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_nass_crop_progress (
    leviathan_slug     string,
    state              string,
    year               bigint,
    date               date,
    week_of_year       bigint,
    pct_planted        double,
    pct_emerged        double,
    pct_good_excellent double,
    pct_poor_very_poor double,
    pct_harvested      double,
    source             string
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/nass_crop_progress/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
