-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/futures_prices/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_futures_prices (
    date             timestamp,
    leviathan_slug   string,
    close            float,
    log_return       float,
    price_z_2yr      float,
    realized_vol_30d float,
    momentum_60d     float,
    momentum_1yr     float,
    vol_regime       tinyint,
    source           string
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/futures_prices/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
