-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/mpoc_stock_comparison/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_mpoc_stock_comparison (
    country          string,
    oil_type         string,
    year             bigint,
    month            bigint,
    ending_stocks_mt double,
    source           string
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/mpoc_stock_comparison/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
