-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/fred_fx/ (hive partition keys are also in-file).
-- FX-1/FX-2 (projection wave, 2026-08-25): 3 -> 14 crosses. The eleven new pairs are ADDITIVE
-- (column order preserved for the incumbents; the live catalog change is ALTER TABLE ADD COLUMNS,
-- D-4 -- never a REPLACE). The writer (_RATE_COLUMNS) and the F010 contract widened in the same
-- change; new columns are all-null in the physical object until the first post-widening daily fire.
CREATE EXTERNAL TABLE IF NOT EXISTS silver_fred_fx (
    date                   string,
    brl_usd                double,
    brl_usd_pct_change_90d double,
    ars_usd                double,
    ars_usd_pct_change_90d double,
    cny_usd                double,
    cny_usd_pct_change_90d double,
    idr_usd                double,
    idr_usd_pct_change_90d double,
    inr_usd                double,
    inr_usd_pct_change_90d double,
    myr_usd                double,
    myr_usd_pct_change_90d double,
    thb_usd                double,
    thb_usd_pct_change_90d double,
    try_usd                double,
    try_usd_pct_change_90d double,
    aud_usd                double,
    aud_usd_pct_change_90d double,
    cad_usd                double,
    cad_usd_pct_change_90d double,
    zar_usd                double,
    zar_usd_pct_change_90d double,
    mxn_usd                double,
    mxn_usd_pct_change_90d double,
    eur_usd                double,
    eur_usd_pct_change_90d double,
    gbp_usd                double,
    gbp_usd_pct_change_90d double,
    source                 string
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/fred_fx/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
