-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/unica_biweekly_season_history/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_unica_biweekly_season_history (
    harvest_year         string,
    fortnight_seq        bigint,
    fortnight_label      string,
    fortnight_date       date,
    region               string,
    cane_crushed_t       double,
    sugar_produced_t     double,
    ethanol_total_m3     double,
    ethanol_anhydrous_m3 double,
    ethanol_hydrous_m3   double,
    source_idm           string,
    source_position_date string
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/unica_biweekly_season_history/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
