-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/wap_table01/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_wap_table01 (
    release_month  string,
    commodity      string,
    row_label      string,
    marketing_year string,
    vintage_type   string,
    vintage_status string,
    month_abbr     string,
    country        string,
    value_mmt      double
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/wap_table01/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
