-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/fnc_colombia/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_fnc_colombia (
    leviathan_slug string,
    country        string,
    department     string,
    department_raw string,
    year           bigint,
    area_ha        double,
    source         string
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/fnc_colombia/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
