-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/mpoc_exports_by_country/ (hive partition keys are also in-file).
-- D-LD TRANCHE 2 (2026-08-18): 5th column year_ending_date DATE = <year>-12-31, the producer-derived
-- PIT anchor the numbers card guards on (knowledge_semantics data_date, publication_lag_days 60).
-- Hand-staged AHEAD of the producer re-run so config_check.check_numbers_schema_pins can resolve the
-- card's date_col/knowledge_date_col. VERIFIED against the generator's renderer: everything from
-- CREATE onward is byte-identical to what jobs/utils/generate_silver_ddls.py --write emits once the
-- re-run lands the 5-column parquet (name column padded to len('year_ending_date') = 16), so a
-- regeneration is a semantic no-op -- but it rewrites the header to its own first two lines and
-- would DROP this note, so re-add it (or simply leave this file as-is). The byte pin is
-- test_dld_mpoc_exports_prestep.test_the_ddl_create_block_matches_the_generator_house_format.
CREATE EXTERNAL TABLE IF NOT EXISTS silver_mpoc_exports_by_country (
    year             bigint,
    country          string,
    exports_mt       double,
    source           string,
    year_ending_date date
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/mpoc_exports_by_country/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
