-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/mpoc_exports_by_country/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_mpoc_exports_by_country (
    year       bigint,
    country    string,
    exports_mt double,
    source     string
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/mpoc_exports_by_country/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
