-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/unica_monthly_ethanol_sales/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_unica_monthly_ethanol_sales (
    harvest_year         string,
    month_num            bigint,
    month_label          string,
    month_date           string,
    is_partial           boolean,
    total_current_m3     double,
    total_prior_m3       double,
    external_current_m3  double,
    external_prior_m3    double,
    internal_current_m3  double,
    internal_prior_m3    double,
    source_idm           string,
    source_position_date string
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/unica_monthly_ethanol_sales/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
