-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/sagis_weekly_deliveries/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_sagis_weekly_deliveries (
    season              string,
    crop                string,
    week_number         bigint,
    week_ending         string,
    prog_total_mt       double,
    prior_prog_total_mt double,
    pct_of_prior_yr     double,
    z_vs_3yr_avg        double,
    source              string,
    week_ending_date    date
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/sagis_weekly_deliveries/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
