-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/fred_fx/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_fred_fx (
    date                   string,
    brl_usd                double,
    brl_usd_pct_change_90d double,
    ars_usd                double,
    ars_usd_pct_change_90d double,
    cny_usd                double,
    cny_usd_pct_change_90d double,
    source                 string
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/fred_fx/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
