-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/weather/source=noaa_iod/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_noaa_iod (
    year                  bigint,
    month                 bigint,
    date                  timestamp,
    dmi_value             float,
    iod_dmi_3month_avg    float,
    iod_phase             string,
    iod_dmi_ethiopia_lag4 float,
    source                string
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/weather/source=noaa_iod/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
