-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/psd/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_psd (
    leviathan_slug            string,
    country                   string,
    market_year               smallint,
    wasde_release_month       tinyint,
    release_date              string,
    beginning_stocks_mt       double,
    production_mt             double,
    imports_mt                double,
    exports_mt                double,
    ending_stocks_mt          double,
    consumption_mt            double,
    area_harvested_1000ha     double,
    yield_mt_ha               double,
    su_ratio                  double,
    su_ratio_yoy_delta        double,
    production_mt_revision    double,
    ending_stocks_mt_revision double,
    consumption_mt_revision   double
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/psd/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
