-- silver_pink_sheet - frozen Athena DDL compared by jobs/utils/validate_athena_ddl_drift.py.
-- Flat table over silver/pink_sheet/.
--
-- CANONICAL COLUMN ORDER = LIVE GLUE CATALOG ORDER. SILVER-F063 (2026-08-20) appended the 44
-- SERIES-WIDENING columns (22 price legs + 22 _zscore_5yr twins) AFTER latest_release_ym, which
-- keeps ordinals 0-35 exactly as shipped -- the migration is a pure ADD COLUMNS, never a REPLACE.
-- Unlike silver_conab_coffee this file does NOT diverge from physical-parquet order: the producer
-- writes SILVER_COLUMNS in this same append-only order, so catalog order == footer order.
-- Kept byte-consistent with sql/athena/ddl_generated/silver_pink_sheet.sql (the registry render).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_pink_sheet (
    date                                timestamp,
    year                                bigint,
    month                               bigint,
    urea_usd_mt                         double,
    dap_usd_mt                          double,
    potassium_usd_mt                    double,
    natural_gas_us_usd_mmbtu            double,
    natural_gas_eu_usd_mmbtu            double,
    phosphate_rock_usd_mt               double,
    brent_crude_usd_bbl                 double,
    blended_npk_index                   double,
    soybeans_usd_t                      double,
    soybean_oil_usd_t                   double,
    soybean_meal_usd_t                  double,
    palm_oil_cpo_usd_t                  double,
    raw_sugar_world_usd_t               double,
    wheat_us_hrw_usd_t                  double,
    wheat_us_srw_usd_t                  double,
    rapeseed_oil_usd_t                  double,
    urea_usd_mt_zscore_5yr              double,
    dap_usd_mt_zscore_5yr               double,
    potassium_usd_mt_zscore_5yr         double,
    natural_gas_us_usd_mmbtu_zscore_5yr double,
    natural_gas_eu_usd_mmbtu_zscore_5yr double,
    phosphate_rock_usd_mt_zscore_5yr    double,
    brent_crude_usd_bbl_zscore_5yr      double,
    blended_npk_index_zscore_5yr        double,
    soybeans_usd_t_zscore_5yr           double,
    soybean_oil_usd_t_zscore_5yr        double,
    soybean_meal_usd_t_zscore_5yr       double,
    palm_oil_cpo_usd_t_zscore_5yr       double,
    raw_sugar_world_usd_t_zscore_5yr    double,
    wheat_us_hrw_usd_t_zscore_5yr       double,
    wheat_us_srw_usd_t_zscore_5yr       double,
    rapeseed_oil_usd_t_zscore_5yr       double,
    latest_release_ym                   string,
    coconut_oil_usd_t                   double,
    groundnuts_usd_t                    double,
    groundnut_oil_usd_t                 double,
    palm_kernel_oil_usd_t               double,
    fish_meal_usd_t                     double,
    sunflower_oil_usd_t                 double,
    barley_usd_t                        double,
    sorghum_usd_t                       double,
    orange_usd_t                        double,
    cotton_a_index_usd_t                double,
    rubber_rss3_usd_t                   double,
    coffee_arabica_usd_t                double,
    coffee_robusta_usd_t                double,
    cocoa_usd_t                         double,
    rice_thai_5pct_usd_t                double,
    maize_usd_t                         double,
    raw_sugar_eu_usd_t                  double,
    raw_sugar_us_usd_t                  double,
    beef_usd_t                          double,
    chicken_usd_t                       double,
    tsp_usd_mt                          double,
    copper_usd_mt                       double,
    coconut_oil_usd_t_zscore_5yr        double,
    groundnuts_usd_t_zscore_5yr         double,
    groundnut_oil_usd_t_zscore_5yr      double,
    palm_kernel_oil_usd_t_zscore_5yr    double,
    fish_meal_usd_t_zscore_5yr          double,
    sunflower_oil_usd_t_zscore_5yr      double,
    barley_usd_t_zscore_5yr             double,
    sorghum_usd_t_zscore_5yr            double,
    orange_usd_t_zscore_5yr             double,
    cotton_a_index_usd_t_zscore_5yr     double,
    rubber_rss3_usd_t_zscore_5yr        double,
    coffee_arabica_usd_t_zscore_5yr     double,
    coffee_robusta_usd_t_zscore_5yr     double,
    cocoa_usd_t_zscore_5yr              double,
    rice_thai_5pct_usd_t_zscore_5yr     double,
    maize_usd_t_zscore_5yr              double,
    raw_sugar_eu_usd_t_zscore_5yr       double,
    raw_sugar_us_usd_t_zscore_5yr       double,
    beef_usd_t_zscore_5yr               double,
    chicken_usd_t_zscore_5yr            double,
    tsp_usd_mt_zscore_5yr               double,
    copper_usd_mt_zscore_5yr            double
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/pink_sheet/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
