-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/wap_table01_revisions/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_wap_table01_revisions (
    release_month       string,
    commodity           string,
    row_label           string,
    marketing_year      string,
    vintage_type        string,
    vintage_status      string,
    month_abbr          string,
    country             string,
    value_mmt           double,
    prior_release_month string,
    prior_value_mmt     double,
    revision_mmt        double
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/wap_table01_revisions/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
