-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/unica_corn_ethanol/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_unica_corn_ethanol (
    harvest_year           string,
    fortnight_seq          bigint,
    fortnight_label        string,
    fortnight_date         date,
    anhydrous_quinzenal_kl double,
    hydrous_quinzenal_kl   double,
    total_quinzenal_kl     double,
    anhydrous_accum_kl     double,
    hydrous_accum_kl       double,
    total_accum_kl         double,
    source_idm             string,
    source_position_date   string
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/unica_corn_ethanol/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
