-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/food_cpi/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_food_cpi (
    country_iso    string,
    country_name   string,
    year           bigint,
    cpi_yoy_pct    float,
    cpi_yoy_z_5yr  float,
    cpi_yoy_z_10yr float,
    cpi_available  tinyint,
    source         string
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/food_cpi/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
