-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/weather/source=noaa_oni/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_noaa_oni (
    year                   bigint,
    month                  bigint,
    season                 string,
    oni_anom               double,
    phase                  string,
    oni_lag3               double,
    oni_lag6               double,
    oni_lag9               double,
    oni_lag12              double,
    el_nino_flag           tinyint,
    la_nina_flag           tinyint,
    la_nina_brazil_flag    tinyint,
    argentina_la_nina_flag tinyint,
    source                 string
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/weather/source=noaa_oni/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
