-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/weather/source=modis_ndvi/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_modis_ndvi (
    date              date,
    year              smallint,
    period            tinyint,
    commodity         string,
    country           string,
    region            string,
    latitude          float,
    longitude         float,
    ndvi_raw          float,
    ndvi              float,
    pixel_reliability tinyint,
    ndvi_z_score      float,
    baseline_mean     float,
    baseline_std      float,
    ingest_date       string
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/weather/source=modis_ndvi/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
