-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/cot/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_cot (
    report_date     string,
    leviathan_slug  string,
    open_interest   bigint,
    mm_long         bigint,
    mm_short        bigint,
    mm_spread       bigint,
    mm_net          bigint,
    mm_pct_oi       double,
    mm_net_z_3yr    double,
    mm_pct_oi_z_3yr double,
    source          string
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/cot/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
