-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/conab_coffee/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_conab_coffee (
    commodity                         string,
    country                           string,
    safra_year                        bigint,
    survey_number                     bigint,
    region                            string,
    area_in_production_ha             double,
    yield_bags_per_ha                 double,
    production_thousand_bags          double,
    production_revision_thousand_bags double,
    source                            string
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/conab_coffee/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
