-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/icco_cocoa/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_icco_cocoa (
    cocoa_year          string,
    latest_release_date string,
    production_kt       double,
    grindings_kt        double,
    end_stocks_kt       double,
    surplus_deficit_kt  double,
    su_ratio            double,
    grindings_3yr_trend double,
    grindings_trend_dev double,
    source              string
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/icco_cocoa/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
