-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.
-- Flat table over silver/mpoc_trade_stats_monthly/ (hive partition keys are also in-file).
CREATE EXTERNAL TABLE IF NOT EXISTS silver_mpoc_trade_stats_monthly (
    year       bigint,
    month      bigint,
    exports_mt double,
    imports_mt double,
    source     string
)
STORED AS PARQUET
LOCATION 's3://leviathan-dev-shahem-001/silver/mpoc_trade_stats_monthly/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');
