#!/usr/bin/env python3
"""Regenerate the CHAIN ENGINE S3-shape mini-decks LOCALLY (CHAIN_ENGINE_PLAN sec 6.1).

The ON/OFF arm split, one-env-per-run (deck:784 precedent): the chain deck runs under ONE process env, so the
chain_fired-pinning rows (ON arm) and the no-pin regress row (OFF arm) live in SEPARATE mini-decks -- a deck can
never carry mixed-flag pins in one run. Each output is the `{queries: [...]}` mapping shape the harness loads.

This regenerates the two arm yamls DETERMINISTICALLY from the master deck (configs/graphrag/
eval_queries_v4_cascade.yaml) so they never drift from the source rows. S3 UPLOAD is the main loop's job (the
download-then-run idiom); this only writes the local artifacts. Gitignored (configs/graphrag/) -> the main loop
byte-copies them to the Desktop mirror.

    python scripts/graphrag/gen_chain_minidecks.py        # writes eval_queries_chain_{on,off}.yaml
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

_CFG = Path(__file__).resolve().parents[2] / "configs" / "graphrag"
_MASTER = _CFG / "eval_queries_v4_cascade.yaml"

# The arm membership (by row id, FILE ORDER preserved). ON = every chain_fired-pinning row (the 3 positives + the
# engine-dark negative); OFF = the no-pin regress row (the flag-off arm of the flagship question).
_ON_IDS = ["chain_wheat_area_su_pos", "chain_corn_safrinha_pos", "chain_coffee_control_pos", "chain_partial_neg"]
_OFF_IDS = ["chain_regress_flag_off"]

_HEADER = ("# GENERATED by scripts/graphrag/gen_chain_minidecks.py from eval_queries_v4_cascade.yaml -- DO NOT\n"
           "# hand-edit (regenerate instead). CHAIN ENGINE mini-deck, {arm} arm (CHAIN_ENGINE_PLAN sec 6.1).\n"
           "# {arm_note}\n")
_ARM_NOTE = {
    "ON": "Run with GRAPHRAG_CASCADE_CHAIN=on + the G5-lane env (GRAPHRAG_NUMBERS_BACKEND=pg): the chain_fired "
          "pins are LIVE only with the seam alive; a parity WARNING invalidates the run.",
    "OFF": "Run flag-OFF (GRAPHRAG_CASCADE_CHAIN absent): the regress row keeps only env-agnostic register + "
           "PIT pins (no chain pin -- the one-env-per-run rule).",
}


def _write_arm(rows: list[dict], ids: list[str], arm: str, out: Path) -> int:
    by_id = {r.get("id"): r for r in rows}
    missing = [i for i in ids if i not in by_id]
    if missing:
        raise SystemExit(f"gen_chain_minidecks: master deck is missing rows {missing}")
    picked = [by_id[i] for i in ids]                     # FILE-ORDER-stable (ids listed in file order)
    body = yaml.safe_dump({"queries": picked}, sort_keys=False, allow_unicode=False, width=120)
    out.write_text(_HEADER.format(arm=arm, arm_note=_ARM_NOTE[arm]) + body, encoding="utf-8")
    return len(picked)


def main() -> int:
    doc = yaml.safe_load(_MASTER.read_text(encoding="utf-8")) or {}
    rows = doc.get("queries") or []
    n_on = _write_arm(rows, _ON_IDS, "ON", _CFG / "eval_queries_chain_on.yaml")
    n_off = _write_arm(rows, _OFF_IDS, "OFF", _CFG / "eval_queries_chain_off.yaml")
    print(f"wrote eval_queries_chain_on.yaml ({n_on} rows), eval_queries_chain_off.yaml ({n_off} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
