"""Fetch USDA FAS GAIN commodity report PDFs to raw S3 — generic multi-commodity downloader.

This is the generalized successor to fetch_gain_coffee.py.  It reads a
manifest generated by:
    1. scratch/gain/probe_gain_http.py   (crawler)
    2. scratch/gain/build_manifest.py    (normalise + write YAML)

Manifest location (resolved from --source):
    configs/sources/{source}_archive.yaml

WAF bypass
----------
fas.usda.gov is protected by a TLS-fingerprint WAF that blocks plain Python
requests.  Downloads use curl_cffi impersonating Chrome 124.

Usage
-----
Smoke test (3 PDFs, US only, dry-run first):
    python jobs/ingest/fetch_gain.py --source usda_gain_wheat --dry-run --limit 5 --country-codes US
    python jobs/ingest/fetch_gain.py --source usda_gain_wheat --limit 3 --country-codes US

Full backfill:
    python jobs/ingest/fetch_gain.py --source usda_gain_wheat --skip-existing-s3
"""
from __future__ import annotations

import argparse
import logging
import time
from pathlib import Path

import yaml
from curl_cffi import requests as curl_requests

from leviathan.common.config import get_required_env, load_env
from leviathan.common.logging import get_logger
from leviathan.storage.paths import raw_gain_key
from leviathan.storage.raw_metadata import check_min_file_size, write_raw_s3_metadata
from leviathan.storage.s3 import s3_object_exists, upload_bytes_to_s3

logger = get_logger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_PDF_MAGIC = b"%PDF"
_IMPERSONATE = "chrome124"  # curl_cffi TLS persona — bypasses fas.usda.gov WAF
_MIN_SIZE_KEY = "usda_gain"  # key in constants.MIN_RAW_FILE_SIZES

_CONFIGS_DIR = Path(__file__).parent.parent.parent / "configs" / "sources"


# ---------------------------------------------------------------------------
# HTTP helper
# ---------------------------------------------------------------------------


def _download_pdf(url: str, session: curl_requests.Session, timeout: int = 60) -> bytes:
    resp = session.get(url, impersonate=_IMPERSONATE, timeout=timeout, allow_redirects=True)
    resp.raise_for_status()
    return resp.content


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
    parser = argparse.ArgumentParser(
        description=(
            "Download USDA FAS GAIN report PDFs to raw S3. "
            "Reads URLs from configs/sources/{source}_archive.yaml. "
            "Uses curl_cffi to bypass the fas.usda.gov TLS fingerprint WAF."
        )
    )
    parser.add_argument(
        "--source",
        required=True,
        metavar="SOURCE",
        help=(
            "Source identifier, e.g. 'usda_gain_wheat'. "
            "Manifest is read from configs/sources/{source}_archive.yaml."
        ),
    )
    parser.add_argument(
        "--country-codes",
        default=None,
        metavar="CC,...",
        help=(
            "Comma-separated ISO2 country codes to process, e.g. 'US,FR,AU'. "
            "Default: all countries in the manifest."
        ),
    )
    parser.add_argument(
        "--category",
        default=None,
        metavar="CATEGORY",
        help=(
            "Report category filter, e.g. 'Grain and Feed Annual'. "
            "Default: all categories in the manifest."
        ),
    )
    parser.add_argument(
        "--skip-existing-s3",
        action="store_true",
        help="Skip reports whose S3 key already exists (safe for re-runs).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be downloaded without downloading anything.",
    )
    parser.add_argument(
        "--sleep-seconds",
        type=float,
        default=2.0,
        help="Polite delay between HTTP requests in seconds (default: 2.0).",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        metavar="N",
        help="Process at most N reports — use 3–5 for a smoke test.",
    )
    args = parser.parse_args()

    source = args.source.strip()
    manifest_path = _CONFIGS_DIR / f"{source}_archive.yaml"

    # -----------------------------------------------------------------------
    # Load manifest
    # -----------------------------------------------------------------------
    if not manifest_path.exists():
        raise FileNotFoundError(
            f"Manifest not found: {manifest_path}\n"
            "Generate it first:\n"
            f"  python scratch/gain/probe_gain_http.py --commodity-id NNN --target-countries ...\n"
            f"  python scratch/gain/build_manifest.py --source-name {source}"
        )

    manifest_data = yaml.safe_load(manifest_path.read_text(encoding="utf-8"))
    reports: list[dict] = manifest_data.get("reports", [])
    logger.info("Loaded %d entries from manifest %s", len(reports), manifest_path.name)

    # -----------------------------------------------------------------------
    # Apply filters
    # -----------------------------------------------------------------------
    country_filter: set[str] | None = None
    if args.country_codes:
        country_filter = {c.strip().upper() for c in args.country_codes.split(",")}
        logger.info("Country filter: %s", sorted(country_filter))

    if country_filter:
        reports = [r for r in reports if r.get("country_iso2", "").upper() in country_filter]
        logger.info("%d reports after country filter", len(reports))

    if args.category:
        cat_lower = args.category.lower()
        reports = [r for r in reports if cat_lower in (r.get("category") or "").lower()]
        logger.info("%d reports after category filter '%s'", len(reports), args.category)

    if args.limit:
        reports = reports[: args.limit]

    # -----------------------------------------------------------------------
    # Dry run
    # -----------------------------------------------------------------------
    if args.dry_run:
        print(f"Source:   {source}")
        print(f"Manifest: {manifest_path.name}  ({len(reports)} matching entries)")
        for entry in reports:
            s3_key = raw_gain_key(
                source,
                entry.get("country_iso2", "??"),
                entry.get("publication_date", "????????"),
                entry.get("filename_clean") or entry.get("pdf_url", "").split("/")[-1],
            )
            print(
                f"  {entry.get('country_iso2', '??')}  "
                f"{entry.get('publication_date', '????????')}  "
                f"{entry.get('report_id', '')}  "
                f"→ {s3_key}"
            )
        return

    # -----------------------------------------------------------------------
    # Download & upload
    # -----------------------------------------------------------------------
    load_env()
    bucket = get_required_env("LEVIATHAN_BUCKET")
    region = get_required_env("AWS_REGION")

    uploaded = skipped = errors = 0

    with curl_requests.Session() as session:
        for entry in reports:
            country_iso2 = entry.get("country_iso2", "").upper()
            pub_date = entry.get("publication_date", "")
            pdf_url = entry.get("pdf_url", "")
            filename = entry.get("filename_clean") or pdf_url.split("/")[-1].replace("%20", "_")
            report_id = entry.get("report_id", "")

            if not pdf_url:
                logger.warning("Skipping entry with no pdf_url: %s", entry)
                errors += 1
                continue

            s3_key = raw_gain_key(source, country_iso2, pub_date, filename)

            try:
                if args.skip_existing_s3 and s3_object_exists(bucket, s3_key, region):
                    logger.info("Skipping — already in S3: %s", s3_key)
                    skipped += 1
                    continue

                logger.info(
                    "Downloading %s  %s  %s …",
                    country_iso2,
                    report_id or pub_date,
                    pdf_url,
                )
                pdf_bytes = _download_pdf(pdf_url, session)

                if not pdf_bytes.startswith(_PDF_MAGIC):
                    raise RuntimeError(
                        f"Response is not a valid PDF (missing %%PDF header): {pdf_url}"
                    )
                check_min_file_size(pdf_bytes, _MIN_SIZE_KEY, context=pdf_url)

                upload_bytes_to_s3(pdf_bytes, bucket, s3_key, region)
                write_raw_s3_metadata(
                    bucket, s3_key, pdf_bytes, pdf_url, "application/pdf", region
                )

                logger.info(
                    "Uploaded %s %s  (%.0f KB) → s3://%s/%s",
                    country_iso2,
                    report_id or pub_date,
                    len(pdf_bytes) / 1_024,
                    bucket,
                    s3_key,
                )
                uploaded += 1

            except Exception as exc:  # noqa: BLE001
                logger.error(
                    "Failed %s %s (%s): %s", country_iso2, report_id or pub_date, pdf_url, exc
                )
                errors += 1

            if args.sleep_seconds > 0:
                time.sleep(args.sleep_seconds)

    logger.info(
        "Done. uploaded=%d  skipped=%d  errors=%d", uploaded, skipped, errors
    )
    if errors:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
