"""Fetch USDA FAS GAIN Coffee Annual / Semi-annual report PDFs to raw S3.

Discovery strategy
------------------
All target report URLs are stored in a static manifest generated by:
  1. scratch/gain/probe_gain_api.py --save    (preferred: JSON API)
  2. scratch/gain/probe_gain_playwright.py    (fallback: Playwright crawler)
  3. scratch/gain/build_manifest.py           (normalises + writes the YAML)

Manifest location:
  configs/sources/usda_gain_coffee_archive.yaml

WAF bypass
----------
fas.usda.gov is protected by a TLS-fingerprint WAF that blocks plain Python
``requests``.  Downloads use ``curl_cffi`` impersonating Chrome 124, the same
approach used by fetch_wmt_coffee.py.

Idempotency
-----------
Pass ``--skip-existing-s3`` to skip reports already in S3.  Safe to re-run.
Pass ``--limit 5 --country-codes BR`` for a quick smoke test.
"""
from __future__ import annotations

import argparse
import time
from pathlib import Path

import yaml
from curl_cffi import requests as curl_requests

from leviathan.common.config import get_required_env, load_env
from leviathan.common.logging import get_logger
from leviathan.storage.paths import raw_gain_coffee_key
from leviathan.storage.raw_metadata import check_min_file_size, write_raw_s3_metadata
from leviathan.storage.s3 import s3_object_exists, upload_bytes_to_s3

logger = get_logger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_PDF_MAGIC = b"%PDF"
_IMPERSONATE = "chrome124"  # curl_cffi TLS persona — bypasses fas.usda.gov WAF

_MANIFEST_PATH = (
    Path(__file__).parent.parent.parent
    / "configs"
    / "sources"
    / "usda_gain_coffee_archive.yaml"
)

# ---------------------------------------------------------------------------
# HTTP helper
# ---------------------------------------------------------------------------


def _download_pdf(url: str, session: curl_requests.Session, timeout: int = 60) -> bytes:
    resp = session.get(url, impersonate=_IMPERSONATE, timeout=timeout, allow_redirects=True)
    resp.raise_for_status()
    return resp.content


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Download USDA FAS GAIN Coffee Annual / Semi-annual report PDFs to raw S3. "
            "Reads URLs from configs/sources/usda_gain_coffee_archive.yaml. "
            "Uses curl_cffi to bypass the fas.usda.gov TLS fingerprint WAF."
        )
    )
    parser.add_argument(
        "--country-codes",
        default=None,
        metavar="CC,...",
        help=(
            "Comma-separated ISO2 country codes to process, e.g. 'BR,CO,ET'. "
            "Default: process all countries in the manifest."
        ),
    )
    parser.add_argument(
        "--category",
        default=None,
        metavar="CATEGORY",
        help=(
            "Report category to filter, e.g. 'Coffee Annual'. "
            "Default: all categories in the manifest."
        ),
    )
    parser.add_argument(
        "--skip-existing-s3",
        action="store_true",
        help="Skip reports whose S3 key already exists (safe for re-runs).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be downloaded without downloading anything.",
    )
    parser.add_argument(
        "--sleep-seconds",
        type=float,
        default=2.0,
        help="Polite delay between HTTP requests in seconds (default: 2.0).",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        metavar="N",
        help="Process at most N reports — use 5 for a smoke test.",
    )
    args = parser.parse_args()

    # -----------------------------------------------------------------------
    # Load manifest
    # -----------------------------------------------------------------------
    if not _MANIFEST_PATH.exists():
        raise FileNotFoundError(
            f"Manifest not found: {_MANIFEST_PATH}\n"
            "Generate it first:\n"
            "  python scratch/gain/probe_gain_api.py --save\n"
            "  python scratch/gain/build_manifest.py"
        )

    manifest_data = yaml.safe_load(_MANIFEST_PATH.read_text(encoding="utf-8"))
    reports: list[dict] = manifest_data.get("reports", [])
    logger.info("Loaded %d entries from manifest %s", len(reports), _MANIFEST_PATH.name)

    # -----------------------------------------------------------------------
    # Apply filters
    # -----------------------------------------------------------------------
    country_filter: set[str] | None = None
    if args.country_codes:
        country_filter = {c.strip().upper() for c in args.country_codes.split(",")}
        logger.info("Country filter: %s", sorted(country_filter))

    if country_filter:
        reports = [r for r in reports if r.get("country_iso2", "").upper() in country_filter]
        logger.info("%d reports after country filter", len(reports))

    if args.category:
        cat_lower = args.category.lower()
        reports = [r for r in reports if cat_lower in (r.get("category") or "").lower()]
        logger.info("%d reports after category filter '%s'", len(reports), args.category)

    if args.limit:
        reports = reports[: args.limit]

    # -----------------------------------------------------------------------
    # Dry run
    # -----------------------------------------------------------------------
    if args.dry_run:
        print(f"Manifest: {_MANIFEST_PATH.name}  ({len(reports)} matching entries)")
        for entry in reports:
            print(
                f"  {entry.get('country_iso2', '??')}  "
                f"{entry.get('publication_date', '????????')}  "
                f"{entry.get('report_id', '')}  "
                f"{entry.get('pdf_url', '')}"
            )
        return

    # -----------------------------------------------------------------------
    # Download & upload
    # -----------------------------------------------------------------------
    load_env()
    bucket = get_required_env("LEVIATHAN_BUCKET")
    region = get_required_env("AWS_REGION")

    uploaded = skipped = errors = 0

    with curl_requests.Session() as session:
        for entry in reports:
            country_iso2 = entry.get("country_iso2", "").upper()
            pub_date = entry.get("publication_date", "")
            pdf_url = entry.get("pdf_url", "")
            filename = entry.get("filename_clean") or pdf_url.split("/")[-1].replace("%20", "_")
            report_id = entry.get("report_id", "")

            if not pdf_url:
                logger.warning("Skipping entry with no pdf_url: %s", entry)
                errors += 1
                continue

            s3_key = raw_gain_coffee_key(country_iso2, pub_date, filename)

            try:
                if args.skip_existing_s3 and s3_object_exists(bucket, s3_key, region):
                    logger.info("Skipping — already in S3: %s", s3_key)
                    skipped += 1
                    continue

                logger.info(
                    "Downloading %s  %s  %s …",
                    country_iso2,
                    report_id or pub_date,
                    pdf_url,
                )
                pdf_bytes = _download_pdf(pdf_url, session)

                if not pdf_bytes.startswith(_PDF_MAGIC):
                    raise RuntimeError(
                        f"Response is not a valid PDF (missing %%PDF header): {pdf_url}"
                    )
                check_min_file_size(pdf_bytes, "usda_gain_coffee", context=pdf_url)

                upload_bytes_to_s3(pdf_bytes, bucket, s3_key, region)
                write_raw_s3_metadata(
                    bucket, s3_key, pdf_bytes, pdf_url, "application/pdf", region
                )

                logger.info(
                    "Uploaded %s %s  (%.0f KB) → s3://%s/%s",
                    country_iso2,
                    report_id or pub_date,
                    len(pdf_bytes) / 1_024,
                    bucket,
                    s3_key,
                )
                uploaded += 1

            except Exception as exc:  # noqa: BLE001
                logger.error(
                    "Failed %s %s (%s): %s", country_iso2, report_id or pub_date, pdf_url, exc
                )
                errors += 1

            if args.sleep_seconds > 0:
                time.sleep(args.sleep_seconds)

    logger.info(
        "Done. uploaded=%d  skipped=%d  errors=%d", uploaded, skipped, errors
    )
    if errors:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
