"""Generate Athena DDLs for silver/gold S3 layers from their actual parquet schema.

Emits one ``CREATE EXTERNAL TABLE`` per source into ``sql/athena/ddl/``.  Tables
are flat (no PARTITIONED BY): every source's hive partition keys are also stored
in-file (or are redundant with ``leviathan_slug``), so Athena reads the prefix
recursively and the partition columns appear as regular columns.  This trades
partition pruning for zero projection boilerplate — fine for reference /
inspection tables (the ML path reads the parquet directly, not via Athena).

    python jobs/utils/generate_silver_ddls.py            # write all
    python jobs/utils/generate_silver_ddls.py --create   # also CREATE in Athena
"""
from __future__ import annotations

import argparse
import io
from pathlib import Path

import boto3
import pyarrow.parquet as pq

_BUCKET = "leviathan-dev-shahem-001"
_DDL_DIR = Path(__file__).resolve().parents[2] / "sql" / "athena" / "ddl"

# table_name -> s3 prefix.  Only sources without a hand-written DDL.
_SOURCES = {
    # commodity-agnostic market / macro / fundamentals
    "silver_cot": "silver/cot/",
    "silver_fred_fx": "silver/fred_fx/",
    "silver_futures_prices": "silver/futures_prices/",
    "silver_pink_sheet": "silver/pink_sheet/",
    "silver_psd": "silver/psd/",
    "silver_wap_table01": "silver/wap_table01/",
    "silver_wap_table01_revisions": "silver/wap_table01_revisions/",
    "silver_food_cpi": "silver/food_cpi/",
    # climate teleconnections
    "silver_noaa_oni": "silver/weather/source=noaa_oni/",
    "silver_noaa_iod": "silver/weather/source=noaa_iod/",
    "silver_modis_ndvi": "silver/weather/source=modis_ndvi/",
    # South Africa grain
    "silver_sagis_cec": "silver/sagis_cec/",
    "silver_sagis_weekly_deliveries": "silver/sagis_weekly_deliveries/",
    "silver_sagis_weekly_exports": "silver/sagis_weekly_exports/",
    # production / origin
    "silver_conab_coffee": "silver/conab_coffee/",
    "silver_fnc_colombia": "silver/fnc_colombia/",
    "silver_nass_crop_progress": "silver/nass_crop_progress/",
    "silver_nass_citrus": "silver/nass_citrus/",
    "silver_icco_cocoa": "silver/icco_cocoa/",
    # Malaysian palm council
    "silver_mpoc_exports_by_country": "silver/mpoc_exports_by_country/",
    "silver_mpoc_stock_comparison": "silver/mpoc_stock_comparison/",
    "silver_mpoc_trade_stats_monthly": "silver/mpoc_trade_stats_monthly/",
    # UNICA sugar/ethanol (Brazil)
    "silver_unica_biweekly_season_history": "silver/unica_biweekly_season_history/",
    "silver_unica_corn_ethanol": "silver/unica_corn_ethanol/",
    "silver_unica_monthly_ethanol_sales": "silver/unica_monthly_ethanol_sales/",
    # gold ML layer
    "gold_feature_catalog": "gold/feature_catalog/",
    "gold_training_windows": "gold/training_windows/",
}

_TYPE_MAP = {
    "large_string": "string", "string": "string", "bool": "boolean",
    "double": "double", "float": "float",
    "int64": "bigint", "int32": "int", "int16": "smallint", "int8": "tinyint",
    "date32[day]": "date", "null": "string",
}


def _athena_type(arrow_type: str) -> str:
    t = arrow_type.lower()
    if t.startswith("timestamp"):
        return "timestamp"
    return _TYPE_MAP.get(t, "string")


def _first_parquet(s3, prefix: str) -> str | None:
    for page in s3.get_paginator("list_objects_v2").paginate(Bucket=_BUCKET, Prefix=prefix):
        for o in page.get("Contents", []):
            if o["Key"].endswith(".parquet") and o["Size"] > 0:
                return o["Key"]
    return None


def _ddl_for(s3, table: str, prefix: str) -> str | None:
    key = _first_parquet(s3, prefix)
    if not key:
        return None
    schema = pq.read_schema(io.BytesIO(s3.get_object(Bucket=_BUCKET, Key=key)["Body"].read()))
    cols = [(n, _athena_type(str(t))) for n, t in zip(schema.names, schema.types)]
    width = max(len(n) for n, _ in cols)
    lines = ",\n".join(f"    {n.ljust(width)} {t}" for n, t in cols)
    return (
        f"-- GENERATED by jobs/utils/generate_silver_ddls.py from the live parquet schema.\n"
        f"-- Flat table over {prefix} (hive partition keys are also in-file).\n"
        f"CREATE EXTERNAL TABLE IF NOT EXISTS {table} (\n{lines}\n)\n"
        f"STORED AS PARQUET\n"
        f"LOCATION 's3://{_BUCKET}/{prefix}'\n"
        f"TBLPROPERTIES ('parquet.compression' = 'SNAPPY');\n"
    )


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--create", action="store_true", help="also CREATE the tables in Athena")
    args = ap.parse_args()

    s3 = boto3.client("s3", region_name="us-east-1")
    written = []
    for table, prefix in _SOURCES.items():
        ddl = _ddl_for(s3, table, prefix)
        if ddl is None:
            print(f"  {table}: no parquet at {prefix} — skipped")
            continue
        (_DDL_DIR / f"{table}.sql").write_text(ddl, encoding="utf-8")
        written.append((table, ddl))
        print(f"  wrote {table}.sql")

    if args.create:
        import sys
        sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
        from jobs.run_athena_ddl import _DATABASE, _run_query
        athena = boto3.client("athena", region_name="us-east-1")
        for table, ddl in written:
            ok, msg = _run_query(athena, ddl, database=_DATABASE)
            print(f"  CREATE {table}: {'OK' if ok else msg}")

    print(f"\n{len(written)} DDLs written to {_DDL_DIR}")


if __name__ == "__main__":
    main()
