"""Athena DDL generation for gold_feature_spine.

The long-format spine has a permanently fixed six-column schema, so the DDL
never churns when features are added — only the commodity partition enum is
derived from the canonical commodity list.  Regenerate + rerun (idempotent
``IF NOT EXISTS``) only when a commodity is added.

Usage:
    python -m leviathan.features.ddl --bucket leviathan-dev-shahem-001 \
        > sql/athena/ddl/gold_feature_spine.sql
"""
from __future__ import annotations

from leviathan.common.constants import ALL_COMMODITIES

_TEMPLATE = """\
-- GENERATED by leviathan.features.ddl -- do not edit by hand.
-- Long-format feature spine: one row per (commodity, country, crop_year, feature).
-- Schema is fixed; adding features never requires a DDL change.
-- Per-feature transformations & visibility rules: docs/FEATURE_DICTIONARY.md
CREATE EXTERNAL TABLE IF NOT EXISTS gold_feature_spine (
    country     string,                          -- producing country (pipeline convention)
    crop_year   int,                             -- marketing/crop year described
    feature     string,                          -- family[_region[_stage]] -- see FEATURE_DICTIONARY.md
    value       double,                          -- value; NaN = structural missingness (never 0)
    is_label    boolean,                         -- true = training target (label_*), never a model input
    event_time  date                             -- first-knowable date (crop-year start); enforces point-in-time
)
PARTITIONED BY (commodity string)
STORED AS PARQUET
LOCATION 's3://{bucket}/gold/feature_spine/'
TBLPROPERTIES (
    'parquet.compression' = 'SNAPPY',
    'projection.enabled' = 'true',
    'projection.commodity.type' = 'enum',
    'projection.commodity.values' = '{commodities}',
    'storage.location.template' = 's3://{bucket}/gold/feature_spine/commodity=${{commodity}}/'
);
"""


def generate_ddl(bucket: str) -> str:
    return _TEMPLATE.format(
        bucket=bucket,
        commodities=",".join(ALL_COMMODITIES),
    )


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Generate gold_feature_spine DDL")
    parser.add_argument("--bucket", required=True)
    args = parser.parse_args()
    print(generate_ddl(args.bucket))
